#!/bin/bash
VIRTUALENV="$1"
OPEN_SUBLIME="$2"

if [ "$1" == "hello"  ]; then
	echo "hello world"

elif [ "$1" == "mbk" ]; then
	VIRTUALENV=""
	DESTINATION="${GOTO_HOME}"

elif [ "$1" == "example" ]; then
	DESTINATION="${GOTO_HOME}/example-project/"

elif [ "$1" == "collect" ]; then
	DESTINATION="${GOTO_HOME}/collect/"

elif [ "$1" == "dispatch" ]; then
	DESTINATION="${GOTO_HOME}/dispatch/"

elif [ "$1" == "resops" ]; then
	DESTINATION="${GOTO_HOME}/resops/resops/"

else
	echo "Make virtual environment $1 with `\$ mkvirtualenv $1`"
	echo "Changing Directory to GOTO_HOME=${GOTO_HOME}"
	VIRTUALENV=""
	DESTINATION="${GOTO_HOME}/"
fi

echo -e "\nexport WINDOWENV=${VIRTUALENV}">>~/.zshrc
source ~/.zshrc
open -a Terminal $DESTINATION

if [ "$2" == "-s"  ]; then
	subl -n -a $DESTINATION
fi
